FROM debian:bookworm

LABEL org.opencontainers.image.source=https://github.com/CorteXlab/cxlb-docker-gnuradio-3.10
LABEL org.opencontainers.image.description="CortexLab GNU Radio 3.10 image built from a specific GNU Radio Git ref"

ENV APT="apt-get -y"

RUN ${APT} update && ${APT} dist-upgrade

WORKDIR /root

# Set an empty password for root
RUN sed -i -e 's%root:\*:%root:$6$fEFUE2YaNmTEH51Z$1xRO8/ytEYIo10ajp4NZSsoxhCe1oPLIyjDjqSOujaPZXFQxSSxu8LDHNwbPiLSjc.8u0Y0wEqYkBEEc5/QN5/:%' /etc/shadow

# Install SSH server, listening on port 2222
RUN ${APT} install openssh-server
RUN sed -i 's/^#\?[[:space:]]*Port 22$/Port 2222/' /etc/ssh/sshd_config
RUN sed -i 's/^#\?[[:space:]]*PermitEmptyPasswords no$/PermitEmptyPasswords yes/' /etc/ssh/sshd_config
RUN sed -i 's/^#\?[[:space:]]*PermitRootLogin.*$/PermitRootLogin yes/' /etc/ssh/sshd_config
RUN mkdir /run/sshd
RUN chmod 755 /run/sshd

# Tweaks for macOS / Windows
RUN sed -i 's/^#\?[[:space:]]*X11UseLocalhost.*$/X11UseLocalhost no/' /etc/ssh/sshd_config
RUN echo "AddressFamily inet" >> /etc/ssh/sshd_config
RUN touch /root/.Xauthority

# Clone CortexLab build toolchain
RUN ${APT} install git
RUN git clone https://github.com/CorteXlab/cxlb-build-toolchain.git cxlb-build-toolchain.git

# Bypass PEP668 issues
RUN mkdir -p /root/.config/pip && touch /root/.config/pip/pip.conf
RUN echo "\n[global]" >> /root/.config/pip/pip.conf
RUN echo "break-system-packages = true" >> /root/.config/pip/pip.conf

# Build toolchain
ENV BUILD="cxlb-build-toolchain.git/cxlb-build-toolchain -y /usr/bin/python3 -as"
ENV PARMS="cxlb_toolchain_build /cortexlab/toolchains/current"

RUN ${APT} install udev

RUN ${BUILD} uhd=master ${PARMS}
RUN ${BUILD} uhd-firmware ${PARMS}
RUN ${BUILD} volk=main ${PARMS}

RUN ${APT} install python3-pygccxml/bookworm

# --------------------------------------------------
# GNU Radio
# Build from the Git ref supplied during docker build
# --------------------------------------------------

ARG GNURADIO_REF=maint-3.10

RUN echo "Building GNU Radio from ref: ${GNURADIO_REF}"

RUN ${BUILD} gnuradio=${GNURADIO_REF} ${PARMS}

# --------------------------------------------------
# Additional GNU Radio modules
# --------------------------------------------------

RUN ${APT} -t bookworm install nodejs

RUN ${BUILD} gr-bokehgui=master ${PARMS}
RUN ${BUILD} gr-iqbal=master ${PARMS}

# Activate CortexLab toolchain configuration
RUN /cortexlab/toolchains/current/bin/cxlb-toolchain-system-conf

RUN ln -s /cortexlab/toolchains/current/bin/cxlb-toolchain-user-conf \
    /etc/profile.d/cxlb-toolchain-user-conf.sh

# Container default executable
CMD ["/usr/sbin/sshd", "-p", "2222", "-D"]